#! /bin/bash

dir="$(cd "$(dirname "$0")" && pwd)"
dir=${dir%"/Commands"}
cd "$dir"
rm -rf ./build/*
xcodebuild archive \
-scheme MetalDevice \
-configuration Release \
-destination 'generic/platform=iOS' \
-archivePath './build/MetalDevice.framework-iphoneos.xcarchive' \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive \
-scheme MetalDevice \
-configuration Release \
-destination 'generic/platform=iOS Simulator' \
-archivePath './build/MetalDevice.framework-iphonesimulator.xcarchive' \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild -create-xcframework \
-framework './build/MetalDevice.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/MetalDevice.framework' \
-framework './build/MetalDevice.framework-iphoneos.xcarchive/Products/Library/Frameworks/MetalDevice.framework' \
-output './build/MetalDevice.xcframework'
rm -rf ../../Packages/MetalDevice/Sources/*
cp -R ./build/MetalDevice.xcframework ../../Packages/MetalDevice/Sources/MetalDevice.xcframework

echo LISTO!