#!/bin/bash

# Set the input directory containing the images
input_dir="$(cd "$(dirname "$0")" && pwd)"

cd "$input_dir"



# Set the output video file name
output_file="output_video.mp4"

# Use ffmpeg to create the video from the images in the directory
ffmpeg -framerate 25 -pattern_type glob -i "./*.jpg" -c:v libx264 -pix_fmt yuv420p "$output_file"
